server:
  port: 33400

general:
  kafka-topic: trader-updates

spring:
  kafka:
    consumer:
      group-id: midas-core-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.jpmc.midascore.foundation"
        spring.json.value.default.type: "com.jpmc.midascore.foundation.Transaction"

    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  h2:
    console.enabled: true
    datasource:
      url: JDBC:h2:mem:webapp
      driver-class-name: org.h2.Driver
      username: sa
      password: password
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect